language: node_js
node_js:
  - 10
cache:
  - yarn
  - npm
branches:
  only:
    - master
    - stable
    - staging
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
os:
  - linux
script:
  - yarn build
  - yarn test
